<?php
    define('TIMEZONE', $_ENV['TZ']);
    define('BASE_PATH', dirname($_SERVER['SCRIPT_FILENAME']). '/');
    define('SCRIPT_TIMEOUT', 0);
    define('USE_CUSTOM_REMOTE_IP_HEADER', 'HTTP_X_FORWARDED_FOR');
    define('USE_FULLEMAIL_FOR_LOGIN', true);
    define('STATE_MACHINE', 'FILE');
    define('STATE_DIR', '/var/lib/z-push/');
    define('IPC_PROVIDER', '');
    define('LOGBACKEND', 'filelog');
    define('LOGLEVEL', LOGLEVEL_INFO);
    define('LOGAUTHFAIL', true);
    define('LOGUSERLEVEL', LOGLEVEL_DEVICEID);
    $specialLogUsers = array();
    define('LOGFILEDIR', '/var/log/z-push/');
    define('LOGFILE', LOGFILEDIR . 'std.log');
    define('LOGERRORFILE', LOGFILEDIR . 'err.log');
    define('PROVISIONING', false);
    define('LOOSE_PROVISIONING', true);
    define('PROVISIONING_POLICYFILE', 'policies.ini');
    define('SYNC_CONFLICT_DEFAULT', SYNC_CONFLICT_OVERWRITE_PIM);
    define('SYNC_FILTERTIME_MAX', SYNC_FILTERTYPE_ALL);
    define('PING_INTERVAL', 60);
    define('FILEAS_ORDER', SYNC_FILEAS_LASTFIRST);
    define('SYNC_MAX_ITEMS', 512);
    define('UNSET_UNDEFINED_PROPERTIES', false);
    define('SYNC_CONTACTS_MAXPICTURESIZE', 5242880);
    define('ALLOW_WEBSERVICE_USERS_ACCESS', false);
    define('USE_PARTIAL_FOLDERSYNC', false);
    define('PING_LOWER_BOUND_LIFETIME', false);
    define('PING_HIGHER_BOUND_LIFETIME', false);
    define('SYNC_TIMEOUT_MEDIUM_DEVICETYPES', "SAMSUNGGTI");
    define('SYNC_TIMEOUT_LONG_DEVICETYPES',   "iPod, iPad, iPhone, WP, WindowsOutlook, WindowsMail");
    define('RETRY_AFTER_DELAY', 300);
    define('BACKEND_PROVIDER', 'BackendCombined');
    define('SEARCH_PROVIDER', '');
    $additionalFolders = array();
