<?php
	define('TIMEZONE',				(string)	getenv("TZ"));
	define('BASE_PATH', 				dirname($_SERVER['SCRIPT_FILENAME']). '/');
	define('SCRIPT_TIMEOUT',			(int)		getenv("zpush_script_timeout"));
	define('USE_CUSTOM_REMOTE_IP_HEADER',		(string)	getenv("zpush_use_custom_remote_ip_header"));
	define('USE_FULLEMAIL_FOR_LOGIN',		(bool)		constant(getenv("zpush_use_fullemail_for_login")));
	define('STATE_MACHINE',				(string)	getenv("zpush_state_machine"));
	define('STATE_DIR',				(string)	getenv("zpush_state_dir"));
	define('IPC_PROVIDER',				(string)	getenv("zpush_ipc_provider"));
	define('LOGBACKEND',				(string)	getenv("zpush_logbackend"));
	define('LOGLEVEL',	LOGLEVEL_INFO);
	define('LOGUSERLEVEL',	LOGLEVEL_DEVICEID);
// ToDo - make Loglevels configurable
// Idea, not working:	define('LOGUSERLEVEL',	constant(getenv("zpush_loguserlevel")));
	define('LOGAUTHFAIL',				(string)	getenv("zpush_logauthfail"));
	$specialLogUsers = array();
	define('LOGFILEDIR',				(string)	getenv("zpush_logfiledir"));
	define('LOGFILE', 		LOGFILEDIR .	(string) getenv("zpush_logfile"));
	define('LOGERRORFILE', 		LOGFILEDIR . 	(string) getenv("zpush_logerrorfile"));
	define('PROVISIONING',				(bool)		constant(getenv("zpush_provisioning")));
	define('LOOSE_PROVISIONING',			(bool)		constant(getenv("zpush_loose_provisioning")));
	define('PROVISIONING_POLICYFILE',		(string)	getenv("zpush_provisioning_policyfile"));
// ToDo - as above, make constants configurable
//	define('SYNC_CONFLICT_DEFAULT',			constant(getenv("zpush_sync_conflict_default")));
//	define('SYNC_FILTERTIME_MAX',			constant(getenv("zpush_sync_filtertime_max")));
	define('SYNC_CONFLICT_DEFAULT',	SYNC_CONFLICT_OVERWRITE_PIM);
	define('SYNC_FILTERTIME_MAX',	SYNC_FILTERTYPE_ALL);
	define('PING_INTERVAL',				(int)		getenv("zpush_ping_intervall"));
//	define('FILEAS_ORDER',				constant(getenv("zpush_fileas_order")));
	define('FILEAS_ORDER',	SYNC_FILEAS_LASTFIRST);
	define('SYNC_MAX_ITEMS',			(int)		getenv("zpush_sync_max_items"));
	define('UNSET_UNDEFINED_PROPERTIES',		(bool)		constant(getenv("zpush_unset_undefined_properties")));
	define('SYNC_CONTACTS_MAXPICTURESIZE',		(int)		getenv("zpush_sync_contacts_maxpicturesize"));
	define('ALLOW_WEBSERVICE_USERS_ACCESS',		(bool)		constant(getenv("zpush_allow_webservice_users_access")));
	define('USE_PARTIAL_FOLDERSYNC',		(bool)		constant(getenv("zpush_use_partial_foldersync")));
	define('PING_LOWER_BOUND_LIFETIME',		(bool)		constant(getenv("zpush_ping_lower_bound_lifetime")));
	define('PING_HIGHER_BOUND_LIFETIME',		(bool)		constant(getenv("zpush_ping_higher_bound_lifetime")));
	define('SYNC_TIMEOUT_MEDIUM_DEVICETYPES',	(string)	getenv("zpush_sync_timeout_medium_devicetypes"));
	define('SYNC_TIMEOUT_LONG_DEVICETYPES',		(string)	getenv("zpush_sync_timeout_long_devicetypes"));
	define('RETRY_AFTER_DELAY',			(int)		getenv("zpush_retry_after_delay"));
	define('BACKEND_PROVIDER',			(string)	getenv("zpush_backend_provider"));
	define('SEARCH_PROVIDER',			(string)	getenv("zpush_search_provider"));
	$additionalFolders = array();
